config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :blogs
  devise_for :blogs, controllers: {
    registrations: 'blogs/registrations'
  }
  root to: 'blogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
  
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs
  mount_uploader :avatar, AvatarUploader
  validates :gender, presence: true
  enum gender: { male: 0, female: 1, other: 2 }
  

  private 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
    before_action :authenticate_user!
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_blog, only: [:edit, :update, :destroy]
    def index
        @blogs = Blog.all
    end
      

    def show
        @blog = Blog.find(params[:id])
    end
    
    def new
        @blog = current_user.blogs.build
    end

    def create
        @blog = current_user.blogs.build(blog_params)
        @blog.user = current_user
        @blog.avatar = params[:blog][:avatar] if params[:blog][:avatar]
        if params[:user] && params[:user][:gender]
            @blog = current_user
            @blog.user.gender = params[:user][:gender]
        end
        if @blog.save
            flash[:success] = 'Blog post was successfully created.'
            redirect_to blogs_path
        else
            flash.now[:error] = 'There was an error creating the blog post.'
            render :new
            # redirect_to blogs_path, alert: 'Failed to create task!'
        end
    end

    def edit
    end
  
    def update
        if @blog.update(blog_params)
          redirect_to blogs_path(@blog)
        else
          render :edit
        end
    end

    def destroy
        # @blog = Blog.find(params[:id])
        @blog.destroy
        redirect_to blogs_path, notice: 'Blog was successfully deleted.'
    end



    private

    def blog_params
        params.require(:blog).permit(:title, :content, :image, :avatar, user_attributes: [:gender])
    end

    def set_blog
        @blog = current_user.blogs.find(params[:id])
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Blogs::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Blogs::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Blogs::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # def create
  #   build_resource(sign_up_params)
  #   resource.avatar = params[:user][:avatar] if params[:user][:avatar] # Set avatar from form

  #   resource.save
  #   if resource.errors.empty?
  #     sign_in(resource)
  #     render json: { user: resource }
  #   else
  #     render json: { error: resource.errors.full_messages }, status: :unprocessable_entity
  #   end
  # end

  protected

  def sign_up_params
    params.require(:user).permit(:gender, :email, :password, :password_confirmation, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :avatar, :gender)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Blogs::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Blogs::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog, html: { multipart: true } do |f| %>
  
  <%= f.file_field :avatar %>
  <%= f.submit %>
<% end %>

app/views/blogs/_image_form.html.erb
<%= form_with(model: @blog, local: true, html: { class: "image-form" }) do |form| %>
  <label for="blog_image">Upload Image:</label>
  <%= form.file_field :image %>
  <%= form.submit 'Upload Image' %>
<% end %>

app/views/blogs/edit.html.erb
<!-- app/views/blogs/edit.html.erb -->
<h1>Edit Blog Post</h1>
<%= render 'image_form' %> <!-- Render the image form partial -->
<%= form_with(model: @blog, url: blog_path(@blog), local: true, method: :patch) do |form| %>
  <%= form.text_field :title, placeholder: 'Title', value: @blog.title %>
  <%= form.text_area :text, placeholder: 'Text', value: @blog.text %>



  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>

  <%= form.submit 'Update Blog Post' %>

  <!--div class = "field">
    <%= image_tag(resource.avatar_thumbnail) if resource.avatar.attached? %>
  </div-->
<% end %>

app/views/blogs/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Tailwind CSS -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.15/dist/tailwind.min.css" rel="stylesheet">
    <title>My Blog</title>
    <style>
        /* Internal CSS */
        body {
            font-family: Arial, sans-serif;
            background-color: #f7f7f7;
            color: #333;
        }
        
        .post {
            margin-bottom: 20px;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        
        .post h2 {
            color: #3498db;
        }
        
        .post .meta {
            color: #777;
            font-size: 14px;
        }
        
        .read-more {
            color: #e74c3c;
            text-decoration: underline;
        }

        .blog-title {
            color: blue;    /* Set the color to blue */
            font-weight: bold;   /* Set the font weight to bold */
            font-size: 24px;     /* Increase the font size (adjust as needed) */
        }
        
        .meta {
            color: #777;
            font-size: 14px;
        }

        footer {
            text-align: center;
            padding: 10px;
            background-color: #2c3e50;
            color: #fff;
        }
    </style>
</head>
<body>
    <header class="bg-blue-600 text-white py-4">
        <h1 class="text-2xl text-center">My Blog</h1>
        <nav class="text-center">
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#" class="text-white">Home</a></li>
                <li class="list-inline-item"><a href="#" class="text-white">About</a></li>
                <li class="list-inline-item"><a href="#" class="text-white">Contact</a></li>
            </ul>
        </nav>
    </header>
    


    <div class="container">
        <!--h1>Blog Posts</h1-->
        <%= form_with(model: Blog.new, url: blogs_path, local: true, multipart: true) do |form| %>
            <%= form.text_field :title, placeholder: "Enter title", required: true %>
            <%= form.text_area :content, placeholder: "Enter content", required: true %>
            <%= form.file_field :image, accept: "image/*" %>
            <%= form.submit "Create Blog Post" %>
        <% end %>
        <ul id="blogList">
            <% @blogs.each do |blog| %>
                <li>

                    <h3 class="blog-title"><%= blog.title %></h3>
                    <p><%= blog.content %></p>
                    <% if blog.image.present? %>
                        <%= image_tag blog.image.url, alt: blog.title %>
                    <% end %>                   

                    <%= link_to "DESTROY", blog, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
                    <div class="blog">
                        <div class="blog flex items-center">
                            <div class="w-12 h-12 mr-4">
                                <%= image_tag blog.user.avatar.url, class: "rounded-full" if blog.user.avatar.present? %>
                            </div>
                        </div>
                    </div>
                    <p class="meta">
                        Posted by <%= blog.user.email %> on <%= blog.created_at.strftime("%B %d, %Y") %>
                        <p>Gender: <%= blog.user.gender %></p>

                    </p>
                    


                    <br>
                    <br>
                </li>

            <% end %>
        </ul>
    </div>






    <footer class="bg-blue-600 text-white text-center py-2">
        <p>&copy; 2023 My Blog. All rights reserved.</p>
    </footer>
</body>
</html>

app/views/blogs/new.html.erb
<!-- app/views/blogs/new.html.erb -->
<h1>Create a New Blog Post</h1>
<%= render 'image_form' %> <!-- Render the image form partial -->
<%= form_with(model: @blog, url: blogs_path, local: true, html: { class: "your-form-class" }) do |form| %>
  <%= form.text_field :title, placeholder: 'Title' %>
  <!-- %= form.text_area :text, placeholder: 'Text' %-->
  <%= form.text_area :content, placeholder: 'Content' %>
  <%= form.file_field :image %>

  <div class="field">
    <%= form.label :gender %>
    <%= form.select :gender, ['Male', 'Female', 'Other'], prompt: "Select Gender" %>
  </div>
  <%= form.submit 'Create Blog Post' %>
<% end %>

app/views/blogs/show.html.erb
<!--h1><%= @blog.title %></h1>
<p><%= @blog.content %></p>

<%= image_tag @blog.avatar.url %-->


<div class="blog">
  <%= image_tag @blog.avatar.url if @blog.avatar.present? %>
  <h1><%= @blog.title %></h1>
  <p><%= @blog.content %></p>
  <%= image_tag @blog.avatar.url if @blog.avatar.present? %>
  <%= blog.user.gender.capitalize %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogginSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "styles", "data-turbo-track": "reload" %>

    
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js' %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <!--ul>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Log In", new_user_session_path %></li>
    </ul-->
    <!--nav>
      
      <%= link_to 'Home', root_path %>
      <br>
      <%= link_to 'Create New Post', new_blog_path %>
    </nav-->
    

    <nav>
      <ul>
        
        <% if user_signed_in? %>

          <%= button_to 'Log out', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to log out?' } %>

        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>  

    <div class="main-content">
      <%= yield %>
    </div>
    
  </body>
</html>